name: siloq-app
region: nyc

services:
  - name: web
    environment_slug: python
    github:
      branch: main
      repo: Siloq-seo/siloq-app
    
    build_command: |
      pip install -r requirements.txt
    
    run_command: python run.py
    
    http_port: 8080
    
    # ⬇️ HERE'S WHERE THEY GO ⬇️
    instance_count: 1              # Line 38 - Number of containers
    instance_size_slug: basic-xs   # Line 39 - Size of each container
    
    envs:
      - key: DATABASE_URL
        scope: RUN_TIME
        type: SECRET
      - key: REDIS_URL
        scope: RUN_TIME
        type: SECRET
      - key: OPENAI_API_KEY
        scope: RUN_TIME
        type: SECRET
      - key: SECRET_KEY
        scope: RUN_TIME
        type: SECRET
      - key: ENVIRONMENT
        scope: RUN_TIME
        value: production
      - key: PORT
        scope: RUN_TIME
        value: "8080"
    
    # Routes
    routes:
      - path: /

# Optional: Managed Database (recommended for production)
# Uncomment if you want Digital Ocean to manage your database
# databases:
#   - name: siloq-postgres
#     engine: PG
#     version: "16"
#     production: false  # Set to true for production
#     cluster_name: siloq-db-cluster

# Optional: Add Valkey/Redis (we discussed this in previous chat)
# You'll need to create this separately and add the connection string to envs
