"""initial_schema

Revision ID: 8f0e4618a387
Revises: 
Create Date: 2026-01-28 17:01:43.123079

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlalchemy.dialects import postgresql
# Auto-import pgvector if Vector is used
try:
    from pgvector.sqlalchemy import Vector
except ImportError:
    pass

# revision identifiers, used by Alembic.
revision = '8f0e4618a387'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # Initial migration setup: extensions and enum types
    op.execute("CREATE EXTENSION IF NOT EXISTS vector;")
    

    
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('length(trim(name)) > 0', name='chk_org_name_not_empty'),
    sa.CheckConstraint('length(trim(slug)) > 0', name='chk_org_slug_not_empty'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_index('idx_organizations_deleted_at', 'organizations', ['deleted_at'], unique=False)
    op.create_index('idx_organizations_slug', 'organizations', ['slug'], unique=False)
    op.create_table('sites',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('domain', sa.String(), nullable=False),
    sa.Column('site_type', sa.Enum('LOCAL_SERVICE', 'ECOMMERCE', name='site_type_enum', create_type=False), nullable=True),
    sa.Column('geo_coordinates', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('service_area', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('product_sku_pattern', sa.String(), nullable=True),
    sa.Column('currency_settings', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint('length(trim(domain)) > 0', name='chk_site_domain_not_empty'),
    sa.CheckConstraint('length(trim(name)) > 0', name='chk_site_name_not_empty'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('domain')
    )
    op.create_table('api_keys',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('site_id', sa.UUID(), nullable=False),
    sa.Column('key_hash', sa.String(length=64), nullable=False),
    sa.Column('key_prefix', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('scopes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_reason', sa.Text(), nullable=True),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('usage_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('length(trim(key_hash)) = 64', name='chk_key_hash_length'),
    sa.CheckConstraint('length(trim(key_prefix)) >= 8', name='chk_key_prefix_length'),
    sa.CheckConstraint('length(trim(name)) > 0', name='chk_api_key_name_not_empty'),
    sa.CheckConstraint('usage_count >= 0', name='chk_usage_count_non_negative'),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key_hash')
    )
    op.create_index('idx_api_keys_is_active', 'api_keys', ['is_active'], unique=False)
    op.create_index('idx_api_keys_key_hash', 'api_keys', ['key_hash'], unique=False)
    op.create_index('idx_api_keys_site_id', 'api_keys', ['site_id'], unique=False)
    op.create_table('clusters',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('site_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint('length(trim(name)) > 0', name='chk_cluster_name_not_empty'),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('site_id', 'name', name='uniq_cluster_name_per_site')
    )
    op.create_index('idx_clusters_site_id', 'clusters', ['site_id'], unique=False)
    op.create_table('pages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('site_id', sa.UUID(), nullable=False),
    sa.Column('path', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('is_proposal', sa.Boolean(), nullable=False),
    sa.Column('status', sa.Enum('draft', 'pending_review', 'approved', 'published', 'decommissioned', 'blocked', name='content_status', create_type=False), nullable=False),
    sa.Column('authority_score', sa.Float(), nullable=True),
    sa.Column('source_urls', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('governance_checks', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('v2_governance', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('active_widget_id', sa.UUID(), nullable=True),
    sa.Column('widget_config_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('embedding', Vector(1536), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('decommissioned_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('authority_score >= 0.0 AND authority_score <= 1.0', name='chk_authority_score_range'),
    sa.CheckConstraint('length(trim(path)) > 0', name='chk_page_path_not_empty'),
    sa.CheckConstraint('length(trim(title)) > 0', name='chk_page_title_not_empty'),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_pages_is_proposal', 'pages', ['is_proposal'], unique=False)
    op.create_index('idx_pages_site_id', 'pages', ['site_id'], unique=False)
    op.create_index('idx_pages_status', 'pages', ['status'], unique=False)
    op.create_table('projects',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('site_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deletion_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint('length(trim(name)) > 0', name='chk_project_name_not_empty'),
    sa.CheckConstraint('length(trim(slug)) > 0', name='chk_project_slug_not_empty'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'slug', name='uniq_project_slug_per_org'),
    sa.UniqueConstraint('site_id')
    )
    op.create_index('idx_projects_organization_id', 'projects', ['organization_id'], unique=False)
    op.create_index('idx_projects_site_id', 'projects', ['site_id'], unique=False)
    op.create_index('idx_projects_slug', 'projects', ['organization_id', 'slug'], unique=False)
    op.create_table('scans',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('site_id', sa.UUID(), nullable=True),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('domain', sa.Text(), nullable=False),
    sa.Column('scan_type', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('overall_score', sa.Float(), nullable=True),
    sa.Column('grade', sa.String(), nullable=True),
    sa.Column('technical_score', sa.Float(), nullable=True),
    sa.Column('content_score', sa.Float(), nullable=True),
    sa.Column('structure_score', sa.Float(), nullable=True),
    sa.Column('performance_score', sa.Float(), nullable=True),
    sa.Column('seo_score', sa.Float(), nullable=True),
    sa.Column('technical_details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('content_details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('structure_details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('performance_details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('seo_details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('recommendations', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('pages_crawled', sa.Integer(), nullable=True),
    sa.Column('scan_duration_seconds', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint("grade IS NULL OR grade IN ('A+', 'A', 'B+', 'B', 'C+', 'C', 'D+', 'D', 'F')", name='chk_grade_valid'),
    sa.CheckConstraint("scan_type IN ('full', 'quick', 'technical')", name='chk_scan_type_valid'),
    sa.CheckConstraint("status IN ('pending', 'processing', 'completed', 'failed')", name='chk_scan_status_valid'),
    sa.CheckConstraint('content_score IS NULL OR (content_score >= 0.0 AND content_score <= 100.0)', name='chk_content_score_range'),
    sa.CheckConstraint('length(trim(domain)) > 0', name='chk_scan_domain_not_empty'),
    sa.CheckConstraint('length(trim(url)) > 0', name='chk_scan_url_not_empty'),
    sa.CheckConstraint('overall_score IS NULL OR (overall_score >= 0.0 AND overall_score <= 100.0)', name='chk_overall_score_range'),
    sa.CheckConstraint('performance_score IS NULL OR (performance_score >= 0.0 AND performance_score <= 100.0)', name='chk_performance_score_range'),
    sa.CheckConstraint('seo_score IS NULL OR (seo_score >= 0.0 AND seo_score <= 100.0)', name='chk_seo_score_range'),
    sa.CheckConstraint('structure_score IS NULL OR (structure_score >= 0.0 AND structure_score <= 100.0)', name='chk_structure_score_range'),
    sa.CheckConstraint('technical_score IS NULL OR (technical_score >= 0.0 AND technical_score <= 100.0)', name='chk_technical_score_range'),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_scans_created_at', 'scans', ['created_at'], unique=False)
    op.create_index('idx_scans_domain', 'scans', ['domain'], unique=False)
    op.create_index('idx_scans_overall_score', 'scans', ['overall_score'], unique=False)
    op.create_index('idx_scans_site_id', 'scans', ['site_id'], unique=False)
    op.create_index('idx_scans_status', 'scans', ['status'], unique=False)
    op.create_table('silos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('site_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('is_finalized', sa.Boolean(), nullable=False),
    sa.Column('finalized_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('entity_type', sa.String(), nullable=True),
    sa.Column('parent_silo_id', sa.UUID(), nullable=True),
    sa.Column('authority_funnel_score', sa.Float(), nullable=True),
    sa.Column('anchor_governance_enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint('authority_funnel_score >= 0.0 AND authority_funnel_score <= 1.0', name='chk_authority_funnel_score_range'),
    sa.CheckConstraint('length(trim(name)) > 0', name='chk_silo_name_not_empty'),
    sa.CheckConstraint('length(trim(slug)) > 0', name='chk_silo_slug_not_empty'),
    sa.CheckConstraint('position >= 1 AND position <= 7', name='chk_silo_position_range'),
    sa.ForeignKeyConstraint(['parent_silo_id'], ['silos.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('site_id', 'position', name='uniq_silo_position_per_site'),
    sa.UniqueConstraint('site_id', 'slug', name='uniq_silo_slug_per_site')
    )
    op.create_index('idx_silos_is_finalized', 'silos', ['is_finalized'], unique=False)
    op.create_index('idx_silos_parent_silo_id', 'silos', ['parent_silo_id'], unique=False)
    op.create_index('idx_silos_position', 'silos', ['site_id', 'position'], unique=False)
    op.create_index('idx_silos_site_id', 'silos', ['site_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=True),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('generation_enabled', sa.Boolean(), nullable=False),
    sa.Column('mfa_enabled', sa.Boolean(), nullable=False),
    sa.Column('mfa_secret', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("role IN ('owner', 'admin', 'editor', 'viewer')", name='chk_user_role_valid'),
    sa.CheckConstraint('length(trim(email)) > 0', name='chk_user_email_not_empty'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index('idx_users_email', 'users', ['email'], unique=False)
    op.create_index('idx_users_organization_id', 'users', ['organization_id'], unique=False)
    op.create_index('idx_users_role', 'users', ['role'], unique=False)
    op.create_table('anchor_links',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('from_page_id', sa.UUID(), nullable=False),
    sa.Column('to_page_id', sa.UUID(), nullable=False),
    sa.Column('anchor_text', sa.String(), nullable=False),
    sa.Column('silo_id', sa.UUID(), nullable=True),
    sa.Column('is_internal', sa.Boolean(), nullable=False),
    sa.Column('authority_passed', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint('authority_passed >= 0.0 AND authority_passed <= 1.0', name='chk_authority_passed_range'),
    sa.CheckConstraint('from_page_id != to_page_id', name='chk_no_self_link'),
    sa.CheckConstraint('length(trim(anchor_text)) > 0', name='chk_anchor_text_not_empty'),
    sa.ForeignKeyConstraint(['from_page_id'], ['pages.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['silo_id'], ['silos.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['to_page_id'], ['pages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('from_page_id', 'to_page_id', 'anchor_text', name='uniq_anchor_link')
    )
    op.create_index('idx_anchor_links_from_page', 'anchor_links', ['from_page_id'], unique=False)
    op.create_index('idx_anchor_links_silo_id', 'anchor_links', ['silo_id'], unique=False)
    op.create_index('idx_anchor_links_to_page', 'anchor_links', ['to_page_id'], unique=False)
    op.create_table('cannibalization_checks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('page_id', sa.UUID(), nullable=False),
    sa.Column('compared_with_id', sa.UUID(), nullable=False),
    sa.Column('similarity_score', sa.Float(), nullable=False),
    sa.Column('threshold_exceeded', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint('page_id != compared_with_id', name='chk_no_self_comparison'),
    sa.CheckConstraint('similarity_score >= 0.0 AND similarity_score <= 1.0', name='chk_similarity_score_range'),
    sa.ForeignKeyConstraint(['compared_with_id'], ['pages.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['page_id'], ['pages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_cannibalization_compared_with', 'cannibalization_checks', ['compared_with_id'], unique=False)
    op.create_index('idx_cannibalization_created_at', 'cannibalization_checks', ['created_at'], unique=False)
    op.create_index('idx_cannibalization_page_id', 'cannibalization_checks', ['page_id'], unique=False)
    op.create_table('cluster_pages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('cluster_id', sa.UUID(), nullable=False),
    sa.Column('page_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint("role IN ('member', 'anchor', 'hub')", name='chk_cluster_page_role_valid'),
    sa.ForeignKeyConstraint(['cluster_id'], ['clusters.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['page_id'], ['pages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cluster_id', 'page_id', name='uniq_cluster_page')
    )
    op.create_index('idx_cluster_pages_cluster_id', 'cluster_pages', ['cluster_id'], unique=False)
    op.create_index('idx_cluster_pages_page_id', 'cluster_pages', ['page_id'], unique=False)
    op.create_table('content_reservations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('site_id', sa.UUID(), nullable=False),
    sa.Column('intent_hash', sa.String(), nullable=False),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('page_id', sa.UUID(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('fulfilled_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('expires_at > created_at', name='chk_reservation_not_expired'),
    sa.CheckConstraint('length(trim(intent_hash)) > 0', name='chk_intent_hash_not_empty'),
    sa.ForeignKeyConstraint(['page_id'], ['pages.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_reservations_expires_at', 'content_reservations', ['expires_at'], unique=False)
    op.create_index('idx_reservations_intent_hash', 'content_reservations', ['site_id', 'intent_hash'], unique=False)
    op.create_index('idx_reservations_site_id', 'content_reservations', ['site_id'], unique=False)
    op.create_table('generation_jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('page_id', sa.UUID(), nullable=False),
    sa.Column('job_id', sa.String(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('error_code', sa.String(length=50), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('max_retries', sa.Integer(), nullable=False),
    sa.Column('total_cost_usd', sa.Float(), nullable=False),
    sa.Column('last_retry_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('structured_output_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('state_transition_history', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('preflight_approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('prompt_locked_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('draft', 'preflight_approved', 'prompt_locked', 'processing', 'postcheck_passed', 'postcheck_failed', 'completed', 'failed', 'ai_max_retry_exceeded')", name='chk_job_status_valid'),
    sa.CheckConstraint('length(trim(job_id)) > 0', name='chk_job_id_not_empty'),
    sa.CheckConstraint('max_retries > 0', name='chk_max_retries_positive'),
    sa.CheckConstraint('retry_count >= 0', name='chk_retry_count_non_negative'),
    sa.CheckConstraint('total_cost_usd >= 0.0', name='chk_total_cost_non_negative'),
    sa.ForeignKeyConstraint(['page_id'], ['pages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_id')
    )
    op.create_index('idx_generation_jobs_job_id', 'generation_jobs', ['job_id'], unique=False)
    op.create_index('idx_generation_jobs_page_id', 'generation_jobs', ['page_id'], unique=False)
    op.create_index('idx_generation_jobs_retry_count', 'generation_jobs', ['retry_count', 'status'], unique=False)
    op.create_index('idx_generation_jobs_status', 'generation_jobs', ['status'], unique=False)
    op.create_index('idx_generation_jobs_total_cost', 'generation_jobs', ['total_cost_usd'], unique=False)
    op.create_table('keywords',
    sa.Column('keyword', sa.Text(), nullable=False),
    sa.Column('page_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint('keyword = lower(trim(keyword))', name='chk_keyword_normalized'),
    sa.CheckConstraint('length(trim(keyword)) > 0', name='chk_keyword_not_empty'),
    sa.ForeignKeyConstraint(['page_id'], ['pages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('keyword'),
    sa.UniqueConstraint('page_id')
    )
    op.create_index('idx_keywords_page_id', 'keywords', ['page_id'], unique=False)
    op.create_table('monthly_usage_summary',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('total_drafts_generated', sa.Integer(), nullable=True),
    sa.Column('total_tokens', sa.Integer(), nullable=True),
    sa.Column('total_cost_usd', sa.Float(), nullable=True),
    sa.Column('total_jobs', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint('month >= 1 AND month <= 12', name='chk_month_range'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'year', 'month', name='uniq_monthly_usage_per_project')
    )
    op.create_index('idx_monthly_usage_project', 'monthly_usage_summary', ['project_id', 'year', 'month'], unique=False)
    op.create_table('page_silos',
    sa.Column('page_id', sa.UUID(), nullable=False),
    sa.Column('silo_id', sa.UUID(), nullable=False),
    sa.Column('is_supporting_page', sa.Boolean(), nullable=False),
    sa.Column('supporting_role', sa.String(), nullable=True),
    sa.Column('authority_weight', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint('authority_weight >= 0.0 AND authority_weight <= 2.0', name='chk_authority_weight_range'),
    sa.ForeignKeyConstraint(['page_id'], ['pages.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['silo_id'], ['silos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('page_id', 'silo_id')
    )
    op.create_index('idx_page_silos_is_supporting', 'page_silos', ['is_supporting_page'], unique=False)
    op.create_table('project_ai_settings',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('api_key_encrypted', sa.Text(), nullable=True),
    sa.Column('api_key_iv', sa.Text(), nullable=True),
    sa.Column('api_key_auth_tag', sa.Text(), nullable=True),
    sa.Column('ai_provider', sa.String(), nullable=True),
    sa.Column('ai_model', sa.String(), nullable=True),
    sa.Column('generation_enabled', sa.Boolean(), nullable=False),
    sa.Column('max_retries', sa.Integer(), nullable=True),
    sa.Column('max_cost_per_job_usd', sa.Float(), nullable=True),
    sa.Column('api_key_last_validated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('api_key_validation_failures', sa.Integer(), nullable=True),
    sa.Column('api_key_last_failure_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint("ai_provider IN ('openai', 'anthropic', 'google')", name='chk_ai_provider_valid'),
    sa.CheckConstraint('max_cost_per_job_usd >= 0.0', name='chk_max_cost_non_negative'),
    sa.CheckConstraint('max_retries > 0', name='chk_max_retries_positive'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('project_id')
    )
    op.create_table('project_entitlements',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('plan_key', sa.Enum('trial', 'blueprint', 'operator', 'agency', 'empire', name='plan_type_enum', create_type=False), nullable=False),
    sa.Column('subscription_status', sa.String(), nullable=True),
    sa.Column('subscription_id', sa.String(), nullable=True),
    sa.Column('stripe_customer_id', sa.String(), nullable=True),
    sa.Column('trial_ends_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('trial_started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('blueprint_activation_purchased', sa.Boolean(), nullable=False),
    sa.Column('blueprint_activated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('blueprint_target_page_id', sa.UUID(), nullable=True),
    sa.Column('max_concurrent_jobs', sa.Integer(), nullable=True),
    sa.Column('max_drafts_per_day', sa.Integer(), nullable=True),
    sa.Column('max_drafts_per_month', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint("subscription_status IN ('active', 'canceled', 'past_due', 'trialing', 'incomplete', 'incomplete_expired')", name='chk_subscription_status_valid'),
    sa.ForeignKeyConstraint(['blueprint_target_page_id'], ['pages.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('project_id')
    )
    op.create_index('idx_project_entitlements_plan_key', 'project_entitlements', ['plan_key'], unique=False)
    op.create_index('idx_project_entitlements_subscription_id', 'project_entitlements', ['subscription_id'], unique=False)
    op.create_table('system_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=True),
    sa.Column('actor_id', sa.UUID(), nullable=True),
    sa.Column('actor_type', sa.String(), nullable=False),
    sa.Column('actor_ip', sa.String(), nullable=True),
    sa.Column('actor_user_agent', sa.Text(), nullable=True),
    sa.Column('event_type', sa.Text(), nullable=False),
    sa.Column('severity', sa.String(), nullable=False),
    sa.Column('action', sa.Text(), nullable=False),
    sa.Column('target_entity_type', sa.Text(), nullable=True),
    sa.Column('target_entity_id', sa.UUID(), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('payload_hash', sa.Text(), nullable=False),
    sa.Column('doctrine_section', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint("actor_type IN ('user', 'system', 'agent')", name='chk_actor_type_valid'),
    sa.CheckConstraint("severity IN ('INFO', 'WARN', 'BLOCK', 'CRITICAL')", name='chk_severity_valid'),
    sa.CheckConstraint('length(trim(action)) > 0', name='chk_action_not_empty'),
    sa.CheckConstraint('length(trim(event_type)) > 0', name='chk_event_type_not_empty'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_system_events_actor', 'system_events', ['actor_id', 'created_at'], unique=False)
    op.create_index('ix_system_events_project_time', 'system_events', ['project_id', 'created_at'], unique=False)
    op.create_index('ix_system_events_severity', 'system_events', ['severity'], unique=False)
    op.create_index('ix_system_events_target', 'system_events', ['target_entity_type', 'target_entity_id'], unique=False)
    op.create_index('ix_system_events_type', 'system_events', ['event_type'], unique=False)
    op.create_table('ai_usage_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('generation_job_id', sa.UUID(), nullable=True),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('model', sa.String(), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=True),
    sa.Column('output_tokens', sa.Integer(), nullable=True),
    sa.Column('total_tokens', sa.Integer(), nullable=True),
    sa.Column('cost_usd', sa.Float(), nullable=True),
    sa.Column('prompt_length', sa.Integer(), nullable=True),
    sa.Column('response_length', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint('cost_usd >= 0.0', name='chk_cost_non_negative'),
    sa.CheckConstraint('input_tokens >= 0 AND output_tokens >= 0 AND total_tokens >= 0', name='chk_tokens_non_negative'),
    sa.ForeignKeyConstraint(['generation_job_id'], ['generation_jobs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_ai_usage_job_id', 'ai_usage_logs', ['generation_job_id'], unique=False)
    op.create_index('idx_ai_usage_project_time', 'ai_usage_logs', ['project_id', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_ai_usage_project_time', table_name='ai_usage_logs')
    op.drop_index('idx_ai_usage_job_id', table_name='ai_usage_logs')
    op.drop_table('ai_usage_logs')
    op.drop_index('ix_system_events_type', table_name='system_events')
    op.drop_index('ix_system_events_target', table_name='system_events')
    op.drop_index('ix_system_events_severity', table_name='system_events')
    op.drop_index('ix_system_events_project_time', table_name='system_events')
    op.drop_index('ix_system_events_actor', table_name='system_events')
    op.drop_table('system_events')
    op.drop_index('idx_project_entitlements_subscription_id', table_name='project_entitlements')
    op.drop_index('idx_project_entitlements_plan_key', table_name='project_entitlements')
    op.drop_table('project_entitlements')
    op.drop_table('project_ai_settings')
    op.drop_index('idx_page_silos_is_supporting', table_name='page_silos')
    op.drop_table('page_silos')
    op.drop_index('idx_monthly_usage_project', table_name='monthly_usage_summary')
    op.drop_table('monthly_usage_summary')
    op.drop_index('idx_keywords_page_id', table_name='keywords')
    op.drop_table('keywords')
    op.drop_index('idx_generation_jobs_total_cost', table_name='generation_jobs')
    op.drop_index('idx_generation_jobs_status', table_name='generation_jobs')
    op.drop_index('idx_generation_jobs_retry_count', table_name='generation_jobs')
    op.drop_index('idx_generation_jobs_page_id', table_name='generation_jobs')
    op.drop_index('idx_generation_jobs_job_id', table_name='generation_jobs')
    op.drop_table('generation_jobs')
    op.drop_index('idx_reservations_site_id', table_name='content_reservations')
    op.drop_index('idx_reservations_intent_hash', table_name='content_reservations')
    op.drop_index('idx_reservations_expires_at', table_name='content_reservations')
    op.drop_table('content_reservations')
    op.drop_index('idx_cluster_pages_page_id', table_name='cluster_pages')
    op.drop_index('idx_cluster_pages_cluster_id', table_name='cluster_pages')
    op.drop_table('cluster_pages')
    op.drop_index('idx_cannibalization_page_id', table_name='cannibalization_checks')
    op.drop_index('idx_cannibalization_created_at', table_name='cannibalization_checks')
    op.drop_index('idx_cannibalization_compared_with', table_name='cannibalization_checks')
    op.drop_table('cannibalization_checks')
    op.drop_index('idx_anchor_links_to_page', table_name='anchor_links')
    op.drop_index('idx_anchor_links_silo_id', table_name='anchor_links')
    op.drop_index('idx_anchor_links_from_page', table_name='anchor_links')
    op.drop_table('anchor_links')
    op.drop_index('idx_users_role', table_name='users')
    op.drop_index('idx_users_organization_id', table_name='users')
    op.drop_index('idx_users_email', table_name='users')
    op.drop_table('users')
    op.drop_index('idx_silos_site_id', table_name='silos')
    op.drop_index('idx_silos_position', table_name='silos')
    op.drop_index('idx_silos_parent_silo_id', table_name='silos')
    op.drop_index('idx_silos_is_finalized', table_name='silos')
    op.drop_table('silos')
    op.drop_index('idx_scans_status', table_name='scans')
    op.drop_index('idx_scans_site_id', table_name='scans')
    op.drop_index('idx_scans_overall_score', table_name='scans')
    op.drop_index('idx_scans_domain', table_name='scans')
    op.drop_index('idx_scans_created_at', table_name='scans')
    op.drop_table('scans')
    op.drop_index('idx_projects_slug', table_name='projects')
    op.drop_index('idx_projects_site_id', table_name='projects')
    op.drop_index('idx_projects_organization_id', table_name='projects')
    op.drop_table('projects')
    op.drop_index('idx_pages_status', table_name='pages')
    op.drop_index('idx_pages_site_id', table_name='pages')
    op.drop_index('idx_pages_is_proposal', table_name='pages')
    op.drop_table('pages')
    op.drop_index('idx_clusters_site_id', table_name='clusters')
    op.drop_table('clusters')
    op.drop_index('idx_api_keys_site_id', table_name='api_keys')
    op.drop_index('idx_api_keys_key_hash', table_name='api_keys')
    op.drop_index('idx_api_keys_is_active', table_name='api_keys')
    op.drop_table('api_keys')
    op.drop_table('sites')
    op.drop_index('idx_organizations_slug', table_name='organizations')
    op.drop_index('idx_organizations_deleted_at', table_name='organizations')
    op.drop_table('organizations')
    # ### end Alembic commands ###
